Script started on Sun 25 Nov 2018 10:43:53 PM PST
]0;mgharlan@zuma:hw4[mgharlan@zuma hw4]$ make all
gcc -ansi -std=c99 -Wall -c PhotoLab_v3.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c  DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -lm PhotoLab.o Image.o FileIO.o -L. -lFilter -o PhotoLab
gcc -ansi -std=c99 -Wall -c -g -DDEBUG -c PhotoLab_v3.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -lm PhotoLab_DEBUG.o Image.o FileIO.o -L. -lFilter -o PhotoLabTest
gcc -ansi -std=c99 -Wall -c -g -DDEBUG -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall -lm Test.o Image.o FileIO.o Advanced.o DIPs.o -o Test
]0;mgharlan@zuma:hw4[mgharlan@zuma hw4]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Sketch the edge of an image
 5: Shuffle an image
 6: Adjust the brightness of an image
 7: Mirror an image horizontally
 8: Adjust the hue of an image
 9: Rotate or flip the image
 10: Resize the image
 11: Saturate the image
 12: Test all functions
 13: Exit
Please make your choice: 12
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
BlackNWhite was tested!
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
Edge was tested!
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle was tested!
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
Brightness was tested!
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HMirror was tested!
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HueRotate was tested!
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.
Saturate was tested!
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
Rotate was tested!
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
Rotate was tested!
HSSOE.ppm was read.
bigresize.ppm was saved. 
bigresize.jpg was stored.
Big Resize was tested!
HSSOE.ppm was read.
smallresize.ppm was saved. 
smallresize.jpg was stored.
Small Resize was tested!

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Sketch the edge of an image
 5: Shuffle an image
 6: Adjust the brightness of an image
 7: Mirror an image horizontally
 8: Adjust the hue of an image
 9: Rotate or flip the image
 10: Resize the image
 11: Saturate the image
 12: Test all functions
 13: Exit
Please make your choice: 13
You exit the program.
]0;mgharlan@zuma:hw4[mgharlan@zuma hw4]$ valgrind --leak-check=full ./PhotoLabTest
==36023== Memcheck, a memory error detector
==36023== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==36023== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==36023== Command: ./PhotoLabTest
==36023== 
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
smallresize.ppm was saved. 
smallresize.jpg was stored.
==36023== 
==36023== HEAP SUMMARY:
==36023==     in use at exit: 0 bytes in 0 blocks
==36023==   total heap usage: 86 allocs, 86 frees, 12,433,008 bytes allocated
==36023== 
==36023== All heap blocks were freed -- no leaks are possible
==36023== 
==36023== For counts of detected and suppressed errors, rerun with: -v
==36023== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;mgharlan@zuma:hw4[mgharlan@zuma hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest Test bw.ppm edge.ppm shuffle.ppm brightness.ppm hmirror.ppm hue.ppm rotate.ppm saturate.ppm smallresize.ppm bigresize.ppm  libFilter.a
]0;mgharlan@zuma:hw4[mgharlan@zuma hw4]$ exit
exit

Script done on Sun 25 Nov 2018 10:45:32 PM PST
